USE ApressFinancial
GO
CREATE UNIQUE CLUSTERED INDEX IX_SharePrices 
ON ShareDetails.SharePrices 
(
    ShareId ASC,
    PriceDate DESC,
    Price
) WITH (STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF,
DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF,
ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = 
OFF, DROP_EXISTING = OFF) ON [PRIMARY]
